module.exports = [
  {
    "styleFamilyId": 23,
    "id": "StkEiv",
    "name": "Guinness Draught",
    "nameDisplay": "Guinness Draught",
    "description": "Swirling clouds tumble as the storm begins to calm, settle, breathe in the moment, then break through the smooth, light head to the bittersweet reward. Unmistakably GUINNESS® beer, stout, or draught , from the first velvet sip to the last, lingering drop. And every deep-dark satisfying mouthful in between. Pure beauty. Pure GUINNESS®.",
    "abv": "4.3",
    "ibu": "50",
    "glasswareId": 5,
    "srmId": 40,
    "availableId": 1,
    "styleId": 23,
    "isOrganic": "N",
    "labels": {
      "icon": "https://s3.amazonaws.com/brewerydbapi/beer/StkEiv/upload_etArOb-icon.png",
      "medium": "https://s3.amazonaws.com/brewerydbapi/beer/StkEiv/upload_etArOb-medium.png",
      "large": "https://s3.amazonaws.com/brewerydbapi/beer/StkEiv/upload_etArOb-large.png"
    },
    "status": "verified",
    "statusDisplay": "Verified",
    "servingTemperature": "cool",
    "servingTemperatureDisplay": "Cool - (8-12C/45-54F)",
    "createDate": "2012-01-03 02:43:19",
    "updateDate": "2015-12-16 03:44:43",
    "glass": {
      "id": 5,
      "name": "Pint",
      "createDate": "2012-01-03 02:41:33"
    },
    "srm": {
      "id": 40,
      "name": "40",
      "hex": "36080A"
    },
    "available": {
      "id": 1,
      "name": "Year Round",
      "description": "Available year round as a staple beer."
    },
    "style": {
      "id": 23,
      "categoryId": 2,
      "category": {
        "id": 2,
        "name": "Irish Origin Ales",
        "createDate": "2012-03-21 20:06:45"
      },
      "name": "Classic Irish-Style Dry Stout",
      "shortName": "Dry Irish Stout",
      "description": "Dry stouts have an initial malt and light caramel flavor profile with a distinctive dry-roasted bitterness in the finish. Dry stouts achieve a dry-roasted character through the use of roasted barley. The emphasis of coffee-like roasted barley and a moderate degree of roasted malt aromas define much of the character. Some slight acidity may be perceived but is not necessary. European hop aroma and flavor should be low or not perceived. Dry stouts have medium-light to medium body. Fruity esters are minimal and overshadowed by malt, high hop bitterness, and roasted barley character. Diacetyl (butterscotch) should be very low or not perceived. Head retention and rich character should be part of its visual character.",
      "ibuMin": "30",
      "ibuMax": "40",
      "abvMin": "3.8",
      "abvMax": "5",
      "srmMin": "40",
      "srmMax": "40",
      "ogMin": "1.038",
      "fgMin": "1.008",
      "fgMax": "1.012",
      "createDate": "2012-03-21 20:06:45",
      "updateDate": "2015-04-07 15:23:51"
    },
    "breweries": [
      {
        "id": "HaPdSL",
        "name": "Guinness",
        "nameShortDisplay": "Guinness",
        "description": "St. James's Gate Brewery (Irish: Grúdlann Gheata Shan Séamuis) is a brewery founded in 1759 in Dublin, Ireland by Arthur Guinness. The company is now a part of Diageo, a company formed via the merger of Guinness  and Grand Metropolitan in 1997. The main product produced at the brewery is Guinness Draft.\r\n\r\nLeased for 9,000 years in 1759 by Arthur Guinness at £45 per year, St. James's Gate has been the home of Guinness ever since. It became the largest brewery in Ireland in 1838, and was the largest in the world in 1914, covering 64 acres. Although no longer the largest brewery in the world, it is still the largest brewer of stout in the world. During the 19th and early 20th centuries, the brewery owned most of the buildings in the surrounding area, including many streets of housing for brewery employees, and offices associated with the brewery. The brewery also made all of its own power using its own power plant.\r\n\r\nThere is an attached exhibition on the 250-year-old history of Guinness, called the Guinness Storehouse.",
        "website": "http://www.guinness.com/",
        "established": "1759",
        "isOrganic": "N",
        "images": {
          "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/HaPdSL/upload_b3rzyZ-icon.png",
          "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/HaPdSL/upload_b3rzyZ-medium.png",
          "large": "https://s3.amazonaws.com/brewerydbapi/brewery/HaPdSL/upload_b3rzyZ-large.png",
          "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/HaPdSL/upload_b3rzyZ-squareMedium.png",
          "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/HaPdSL/upload_b3rzyZ-squareLarge.png"
        },
        "status": "verified",
        "statusDisplay": "Verified",
        "createDate": "2012-01-03 02:41:56",
        "updateDate": "2015-12-22 14:38:48",
        "locations": [
          {
            "id": "9RsQkk",
            "name": "Main Brewery",
            "streetAddress": "109 James's Street",
            "locality": "Dublin City",
            "region": "Dublin",
            "postalCode": "8",
            "website": "http://www.guinness.com/",
            "latitude": 53.34309,
            "longitude": -6.290799,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "micro",
            "locationTypeDisplay": "Micro Brewery",
            "countryIsoCode": "IE",
            "yearOpened": "1759",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:41:56",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "IE",
              "name": "IRELAND",
              "displayName": "Ireland",
              "isoThree": "IRL",
              "numberCode": 372,
              "createDate": "2012-01-03 02:41:33"
            }
          }
        ]
      }
    ]
  },

  {
    "styleFamilyId": 19,
    "id": "WAW2Ar",
    "name": "Black Butte Porter",
    "nameDisplay": "Black Butte Porter",
    "description": "Our flagship beer, Black Butte Porter defined Deschutes as a place intent to follow its own brewing muse. At a time when dark beer was viewed with suspicion, this deep, satiny brew went out and dispelled the myths for a generation of enthusiasts. Black Butte is rich in flavor yet easy to drink, with a creamy, smooth mouth feel. The slight hop bitterness up front only enhances the distinctive chocolate and roasted finish to come. It continues to reap accolades and medals from those who know best.",
    "abv": "5.2",
    "ibu": "30",
    "glasswareId": 5,
    "srmId": 41,
    "availableId": 1,
    "styleId": 18,
    "isOrganic": "N",
    "labels": {
      "icon": "https://s3.amazonaws.com/brewerydbapi/beer/WAW2Ar/upload_XZ4WTT-icon.png",
      "medium": "https://s3.amazonaws.com/brewerydbapi/beer/WAW2Ar/upload_XZ4WTT-medium.png",
      "large": "https://s3.amazonaws.com/brewerydbapi/beer/WAW2Ar/upload_XZ4WTT-large.png"
    },
    "status": "verified",
    "statusDisplay": "Verified",
    "foodPairings": "Salmon & Wild Rice\r\nElk Burger\r\nOnion Soup",
    "createDate": "2012-01-03 02:42:50",
    "updateDate": "2015-12-15 22:22:24",
    "glass": {
      "id": 5,
      "name": "Pint",
      "createDate": "2012-01-03 02:41:33"
    },
    "srm": {
      "id": 41,
      "name": "Over 40",
      "hex": "000000"
    },
    "available": {
      "id": 1,
      "name": "Year Round",
      "description": "Available year round as a staple beer."
    },
    "style": {
      "id": 18,
      "categoryId": 1,
      "category": {
        "id": 1,
        "name": "British Origin Ales",
        "createDate": "2012-03-21 20:06:45"
      },
      "name": "Brown Porter",
      "shortName": "Brown Porter",
      "description": "Brown porters are mid to dark brown (may have red tint) in color. No roast barley or strong burnt/black malt character should be perceived. Low to medium malt sweetness, caramel and chocolate is acceptable along with medium hop bitterness. This is a lightto medium-bodied beer. Fruity esters are acceptable. Hop flavor and aroma may vary from being negligible to medium in character.",
      "ibuMin": "20",
      "ibuMax": "30",
      "abvMin": "4.5",
      "abvMax": "6",
      "srmMin": "20",
      "srmMax": "35",
      "ogMin": "1.04",
      "fgMin": "1.006",
      "fgMax": "1.014",
      "createDate": "2012-03-21 20:06:45",
      "updateDate": "2015-04-07 15:21:43"
    },
    "breweries": [
      {
        "id": "YHij73",
        "name": "Deschutes Brewery",
        "nameShortDisplay": "Deschutes",
        "description": "Founded in 1988, Deschutes Brewery began as a brew pub in downtown Bend, Oregon and is known for such brands as Black Butte Porter, the nation’s number one selling craft porter, and the popular Mirror Pond Pale Ale. In addition to its original Bend pub, this family and employee-owned brewery opened a second pub in Portland’s Pearl District in 2008. The company’s main brewing facility is located on the banks of the Deschutes River and is the nation's 7th largest craft brewery, distributing in 28 states, Washington D.C., and two Canadian provinces. Deschutes Brewery was named one of America’s Best Places to Work in 2013 & 2014 by Outside Magazine.",
        "website": "http://www.deschutesbrewery.com/",
        "established": "1988",
        "isOrganic": "N",
        "images": {
          "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/YHij73/upload_jb2T95-icon.png",
          "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/YHij73/upload_jb2T95-medium.png",
          "large": "https://s3.amazonaws.com/brewerydbapi/brewery/YHij73/upload_jb2T95-large.png",
          "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/YHij73/upload_jb2T95-squareMedium.png",
          "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/YHij73/upload_jb2T95-squareLarge.png"
        },
        "status": "verified",
        "statusDisplay": "Verified",
        "createDate": "2012-01-03 02:41:52",
        "updateDate": "2015-12-22 14:44:24",
        "locations": [
          {
            "id": "pILoJW",
            "name": "Main Brewery",
            "streetAddress": "901 SW Simpson Avenue",
            "locality": "Bend",
            "region": "Oregon",
            "postalCode": "97702",
            "phone": "1-541-385-8606",
            "website": "http://www.deschutesbrewery.com/",
            "latitude": 44.0468512,
            "longitude": -121.3223363,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "tasting",
            "locationTypeDisplay": "Tasting Room",
            "countryIsoCode": "US",
            "yearOpened": "1988",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:41:52",
            "updateDate": "2014-09-11 10:36:23",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "hfm9Wj",
            "name": "Deschutes Brewery Portland Public House",
            "streetAddress": "210 NW 11th Ave",
            "locality": "Portland",
            "region": "Oregon",
            "postalCode": "97209",
            "phone": "(503) 296-4906",
            "website": "http://www.deschutesbrewery.com/locations/portland",
            "hoursOfOperation": "Sun:  11:00am - 11:00pm\r\nWed:  11:00am - 11:00pm\r\nThu:  11:00am - 11:00pm\r\nFri:  11:00am - 12:00am\r\nSat:  11:00am - 12:00am",
            "latitude": 45.524615,
            "longitude": -122.681867,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "brewpub",
            "locationTypeDisplay": "Brewpub",
            "countryIsoCode": "US",
            "yearOpened": "2008",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-09-10 23:38:07",
            "updateDate": "2015-08-18 14:04:30",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "JzUxgA",
            "name": "Deschutes Brewery Bend Public House",
            "streetAddress": "1044 NW Bond St",
            "locality": "Bend",
            "region": "Oregon",
            "postalCode": "97701",
            "phone": "(541) 382-9242",
            "website": "http://www.deschutesbrewery.com/locations/bend",
            "hoursOfOperation": "Wed:  11:00am - 11:00pm\r\nThu:  11:00am - 11:00pm\r\nFri:  11:00am - 12:00am\r\nSat:  11:00am - 12:00am\r\nSun:  11:00am - 10:00pm",
            "latitude": 44.0593763,
            "longitude": -121.3112178,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "brewpub",
            "locationTypeDisplay": "Brewpub",
            "countryIsoCode": "US",
            "yearOpened": "1988",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-09-10 23:39:44",
            "updateDate": "2015-08-18 14:04:40",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          }
        ]
      }
    ]
  },

  {
    "styleFamilyId": 22,
    "id": "FXGCOG",
    "name": "Killian's Irish Red",
    "nameDisplay": "Killian's Irish Red",
    "description": "Killian's Irish Red is a traditional lager with an authentic Irish heritage, based on the Killian family's recipe created for the Killian's brewery in Enniscorthy, Ireland in 1864. Coors acquired the rights to brew and market the product in America and Killian's was introduced to the U.S. in 1981.\r\n\r\nKillian's Irish Red derives its distinctive red-amber color and taste from a special caramel malt that has been roasted at a high temperature longer and more slowly than most malts. There are no coloring agents or artificial additives used in brewing Killian's. The brew is known for its rich amber color and thick, creamy head.",
    "abv": "4.9",
    "glasswareId": 5,
    "availableId": 1,
    "styleId": 22,
    "isOrganic": "N",
    "labels": {
      "icon": "https://s3.amazonaws.com/brewerydbapi/beer/FXGCOG/upload_mVF4s0-icon.png",
      "medium": "https://s3.amazonaws.com/brewerydbapi/beer/FXGCOG/upload_mVF4s0-medium.png",
      "large": "https://s3.amazonaws.com/brewerydbapi/beer/FXGCOG/upload_mVF4s0-large.png"
    },
    "status": "verified",
    "statusDisplay": "Verified",
    "createDate": "2012-01-03 02:43:33",
    "updateDate": "2016-07-19 14:41:44",
    "glass": {
      "id": 5,
      "name": "Pint",
      "createDate": "2012-01-03 02:41:33"
    },
    "available": {
      "id": 1,
      "name": "Year Round",
      "description": "Available year round as a staple beer."
    },
    "style": {
      "id": 22,
      "categoryId": 2,
      "category": {
        "id": 2,
        "name": "Irish Origin Ales",
        "createDate": "2012-03-21 20:06:45"
      },
      "name": "Irish-Style Red Ale",
      "shortName": "Irish Red",
      "description": "Irish-style red ales range from light red-amber-copper to light brown in color. These ales have a medium hop bitterness and flavor. They often don't have hop aroma. Irish-style red ales have low to medium candy-like caramel malt sweetness and may have a balanced subtle degree of roast barley or roast malt character and complexity.  Irish-style Red Ales have a medium body. The style may have low levels of fruity-ester flavor and aroma. Diacetyl should be absent or at very low levels. Chill haze is allowable at cold temperatures. Slight yeast haze is acceptable for bottle-conditioned products.",
      "ibuMin": "20",
      "ibuMax": "28",
      "abvMin": "4",
      "abvMax": "4.5",
      "srmMin": "11",
      "srmMax": "18",
      "ogMin": "1.04",
      "fgMin": "1.01",
      "fgMax": "1.014",
      "createDate": "2012-03-21 20:06:45",
      "updateDate": "2015-04-07 15:23:38"
    },
    "breweries": [
      {
        "id": "avMkil",
        "name": "Coors Brewing Company",
        "nameShortDisplay": "Coors",
        "description": "In 1873, as the United States approached its centennial year, its people were busy building a new kind of nation. It was thirsty work. And that's where Coors Brewing Company came in. When we began in that same year, we were a small, family-owned brewery, located at the foot of the Rocky Mountains. We were busy creating the same kind of crisp, refreshing beer we're known for today. While hundreds of such family-owned breweries have come and gone in the years since, we believe the reasons for our success are simple. We've never compromised on quality in producing our award-winning brews and we've never lost sight of our rich Rocky Mountain heritage. Just as important, we've always believed in doing well by doing good. We treat our employees with respect, we support the local communities where we do business, and we strive to protect the environment. That's just how we do business.",
        "website": "http://www.sabmiller.com/",
        "established": "1895",
        "isOrganic": "N",
        "images": {
          "icon": "https://s3.amazonaws.com/brewerydbapi/brewery/avMkil/upload_loKult-icon.png",
          "medium": "https://s3.amazonaws.com/brewerydbapi/brewery/avMkil/upload_loKult-medium.png",
          "large": "https://s3.amazonaws.com/brewerydbapi/brewery/avMkil/upload_loKult-large.png",
          "squareMedium": "https://s3.amazonaws.com/brewerydbapi/brewery/avMkil/upload_loKult-squareMedium.png",
          "squareLarge": "https://s3.amazonaws.com/brewerydbapi/brewery/avMkil/upload_loKult-squareLarge.png"
        },
        "status": "verified",
        "statusDisplay": "Verified",
        "createDate": "2012-01-03 02:41:51",
        "updateDate": "2015-12-22 14:43:37",
        "locations": [
          {
            "id": "JZk4BM",
            "name": "Golden Brewery",
            "streetAddress": "311 Tenth Street",
            "locality": "Golden",
            "region": "Colorado",
            "postalCode": "80401",
            "phone": "1-866-812-2337",
            "website": "http://www.coors.com/",
            "latitude": 39.759876,
            "longitude": -105.219026,
            "isPrimary": "Y",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "macro",
            "locationTypeDisplay": "Macro Brewery",
            "countryIsoCode": "US",
            "yearOpened": "1873",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2012-01-03 02:41:51",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "LKzaHC",
            "name": "Shenandoah Facility",
            "streetAddress": "5135 South East Side Hwy",
            "locality": "Elkton",
            "region": "Virginia",
            "postalCode": "22827",
            "phone": "(540) 289-8201",
            "website": "http://www.millercoors.com/",
            "latitude": 38.3568877,
            "longitude": -78.6765693,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "2007",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2013-09-21 20:40:25",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "AhsRDX",
            "name": "Albany Brewery",
            "streetAddress": "405 Cordele Road",
            "locality": "Albany",
            "region": "Georgia",
            "postalCode": "31705",
            "website": "http://www.millercoors.com/",
            "latitude": 31.5927553,
            "longitude": -84.0879927,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "1979",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:46:11",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "n1bFMy",
            "name": "Chicago Headquarters",
            "streetAddress": "250 South Wacker Drive",
            "locality": "Chicago",
            "region": "Illinois",
            "postalCode": "60606",
            "website": "http://www.millercoors.com/",
            "latitude": 41.8785888,
            "longitude": -87.6371,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "office",
            "locationTypeDisplay": "Office",
            "countryIsoCode": "US",
            "yearOpened": "2009",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:46:55",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "PLK3WP",
            "name": "Main Brewery",
            "streetAddress": "863 E. Meadow Road",
            "locality": "Charlotte",
            "region": "North Carolina",
            "postalCode": "27289",
            "website": "http://www.millercoors.com/",
            "latitude": 35.1847149,
            "longitude": -80.8125,
            "isPrimary": "N",
            "inPlanning": "Y",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "micro",
            "locationTypeDisplay": "Micro Brewery",
            "countryIsoCode": "US",
            "yearOpened": "1978",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:47:40",
            "updateDate": "2015-01-08 16:23:49",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "1f2rfq",
            "name": "Fort Worth Brewery",
            "streetAddress": "7001 South Freeway",
            "locality": "Fort Worth",
            "region": "Texas",
            "postalCode": "76134",
            "website": "http://www.millercoors.com/",
            "latitude": 32.6433233,
            "longitude": -97.3198541,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "1966",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:48:23",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "GIUTyi",
            "name": "Golden Office",
            "streetAddress": "17735 West 32nd Ave",
            "locality": "Golden",
            "region": "Colorado",
            "postalCode": "80401",
            "website": "http://www.millercoors.com/",
            "latitude": 39.7651047,
            "longitude": -105.200336,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "office",
            "locationTypeDisplay": "Office",
            "countryIsoCode": "US",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:49:19",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "scDI89",
            "name": "Irwindale Brewery",
            "streetAddress": "15801 East First Street",
            "locality": "Irwindale",
            "region": "California",
            "postalCode": "91706",
            "website": "http://www.millercoors.com/",
            "latitude": 34.1216703,
            "longitude": -117.9382061,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "1980",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:51:02",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "Uvw6Ha",
            "name": "Milwaukee Office",
            "streetAddress": "3939 West Highland Blvd",
            "locality": "Milwaukee",
            "region": "Wisconsin",
            "postalCode": "53208",
            "website": "http://www.millercoors.com/",
            "latitude": 43.043906,
            "longitude": -87.961934,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "office",
            "locationTypeDisplay": "Office",
            "countryIsoCode": "US",
            "status": "deleted",
            "statusDisplay": "Deleted",
            "createDate": "2014-04-18 13:51:41",
            "updateDate": "2015-06-17 18:36:55",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "7FeuR1",
            "name": "Milwaukee Brewery",
            "streetAddress": "4000 West State Street",
            "locality": "Milwaukee",
            "region": "Wisconsin",
            "postalCode": "53208",
            "website": "http://www.millercoors.com/",
            "latitude": 43.0422255,
            "longitude": -87.9631211,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "Y",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "1855",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:52:24",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "jZNiaS",
            "name": "Trenton Brewery",
            "streetAddress": "2525 Wayne Madison Road",
            "locality": "Trenton",
            "region": "Ohio",
            "postalCode": "45067",
            "website": "http://www.millercoors.com/",
            "latitude": 39.457537,
            "longitude": -84.485393,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "1991",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:54:13",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          },
          {
            "id": "Lt6Wjt",
            "name": "Watertown Hops Company",
            "streetAddress": "1224 American Way",
            "locality": "Watertown",
            "region": "Wisconsin",
            "postalCode": "53094",
            "website": "http://www.watertownhops.com/",
            "latitude": 43.177416,
            "longitude": -88.760608,
            "isPrimary": "N",
            "inPlanning": "N",
            "isClosed": "N",
            "openToPublic": "N",
            "locationType": "production",
            "locationTypeDisplay": "Production Facility",
            "countryIsoCode": "US",
            "yearOpened": "1989",
            "status": "verified",
            "statusDisplay": "Verified",
            "createDate": "2014-04-18 13:55:40",
            "updateDate": "2014-07-23 19:11:34",
            "country": {
              "isoCode": "US",
              "name": "UNITED STATES",
              "displayName": "United States",
              "isoThree": "USA",
              "numberCode": 840,
              "createDate": "2012-01-03 02:41:33"
            }
          }
        ]
      }
    ]
  }
]